import Head from 'next/head'
import Login from '../components/Login'
import styles from '../styles/Home.module.css'
import { useMoralis } from 'react-moralis';

export default function Home() {
  const { isAuthenticated, logout } = useMoralis();

  if (!isAuthenticated) return <Login />
  return (
    <div className='h-screen'>
      <Head>
        <title>Kenny's Mateverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1>Welcome to the app</h1>
      <button onClick={logout}>Logout</button>
    </div>
  )
}
